Source Code/do_an/Controllers/ImageController.cs
using do_an.Models;
using Microsoft.AspNetCore.Mvc;
using Nancy.Json;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.Dynamic;
using System.IO;

namespace do_an.Controllers
{
    public class ImageController : Controller
    {
        Root items = new Root();
        public IActionResult Index()
        {
            items = items.init();
            return View(items);
        }

        public ActionResult OpenImage(int Id)
        {
            items = items.init();

            var image = items.images.Where(i => i.id == Id).FirstOrDefault();
            return View(image);
        }

        public ActionResult EditImage(int Id)
        {
            items = items.init();

            var image = items.images.Where(i => i.id == Id).FirstOrDefault();
            return View(image);
        }

        public IActionResult FilterImage()
        {
            return View();
        }

        public JsonResult FilterCategory(int fromId, int toId, int categoryId)
        {
            items = items.init();
            var arrCategory = (from category in items.categories
                         where categoryId == category.id
                         select category).ToList();
            var arrAnnotation = (from annotation in items.annotations
                                where annotation.image_id >= fromId
                                where annotation.image_id <= toId
                                where annotation.category_id == categoryId
                                select annotation).ToList();
            var arrImage = (from image in items.images
                           where image.id >= fromId
                           where image.id <= toId
                           select image).ToList();

            return Json(new Root(arrImage,arrCategory,arrAnnotation));
        }

        public JsonResult getAnnotation(int image_id)
        {
            items = items.init();
            var result = from item in items.annotations
                         where item.image_id == image_id
                         select item;

            return Json(result);
        }
        public static bool HasProperty(dynamic obj, string name)
        {
            Type objType = obj.GetType();

            if (objType == typeof(ExpandoObject))
            {
                return ((IDictionary<string, object>)obj).ContainsKey(name);
            }

            return objType.GetProperty(name) != null;
        }


        [HttpPost]
        public async Task<IActionResult> UpdateAnnotation(string annotation_json, int image_id)
        {
            dynamic config = JsonConvert.DeserializeObject<ExpandoObject>(annotation_json, new ExpandoObjectConverter());
            items = items.init();
            List<Annotation> list_anno = items.annotations.Where(i => i.image_id == image_id).ToList();
            dynamic temp;
            foreach (var rect in ((IEnumerable<dynamic>)config.children))
            {
                temp = rect.children;
                //dynamic temp1 = temp[4].attrs;
                foreach(var item in temp)
                {
                    try
                    {
                        dynamic update_bbox = item.attrs;
                        foreach (var item_anno in list_anno)
                        {
                            if (HasProperty(update_bbox, "x") && HasProperty(update_bbox, "y") && HasProperty(update_bbox, "id"))
                            {
                                if (update_bbox.id == item_anno.id.ToString())
                                {
                                    item_anno.bbox[0] = update_bbox.x;
                                    item_anno.bbox[1] = update_bbox.y;
                                    if (HasProperty(update_bbox, "scaleX") && HasProperty(update_bbox, "scaleY"))
                                    {
                                        item_anno.bbox[2] = (double)(update_bbox.width * update_bbox.scaleX);
                                        item_anno.bbox[3] = (double)(update_bbox.height * update_bbox.scaleY);
                                        item_anno.area = (double)(item_anno.bbox[2] * item_anno.bbox[3]);
                                    }else if(HasProperty(update_bbox, "scaleX"))
                                    {
                                        item_anno.bbox[2] = (double)(update_bbox.width * update_bbox.scaleX);
                                        //item_anno.bbox[3] = (double)(update_bbox.height * update_bbox.scaleY);
                                        item_anno.area = (double)(item_anno.bbox[2] * item_anno.bbox[3]);
                                    }
                                    items.UpdateAnnotation(items.annotations, item_anno);
                                }
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        throw;
                    }
                }
            }
            //var itemmm = items.annotations;
            items.deleteJson();
            items.writeJson(items);
            return this.Ok("Form Data received!");
        }
    }
}

Source Code/do_an/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - do_an</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/do_an.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawnsome/css/all.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">do_an</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Image" asp-action="Index">Image</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="container-fluid">
        @RenderSection("EditSection",false)
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class=col-10 style="height:auto">
                @RenderSection("ImageSection", false)
            </div>
            <div class=col-2>
                @RenderSection("RightSection", false)
            </div>
        </div>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - do_an - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @RenderSection("JsSection", false)
</body>
</html>